// Commander Database - Sri Lanka Defense Power
const DB={
army:[
{n:"26th",nm:"Lt Gen Nilantha Premaratne",rk:"Lieutenant General",t:"Aug 2026 – Present",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/comd/commander_no1.webp",e:"St. Servatius' College, Matara; SLMA; Naval Postgraduate School California (MA Security Studies); Univ of Kelaniya (MDefS); Artillery Young Officers Course India; Advanced Gunnery Course Pakistan; Army Cmd & Staff Course; Bn Commanders' Course China",j:"Joined Regular Force 14 Jul 1990 (RI 34); commissioned 6 Jun 1992",c:"Battery Cdr 6th Field Regt SLA; CO 16th Regt SLA; Cdr 551 Inf Brigade; GOC 23 Div; Cdr SF (East); Cmdt SLAVF; Adjutant General; Deputy CoS; CoS; Commander of the Army",a:"Authored 'The Impact of Changing External Conditions on Counter Insurgency: The Sri Lankan Experience'; RSP x2; UN MINURSO Military Observer",w:"Current commander—assumed office 1 Aug 2026",d:"RSP (x2), USP",u:"Sri Lanka Artillery"},
{rankBadge:"https://upload.wikimedia.org/wikipedia/commons/9/9b/Sri_Lanka-army-OF-8.svg",n:"25th",nm:"Lt Gen Lasantha Rodrigo",rk:"Lieutenant General",t:"Dec 2024 – Jul 2026",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Lasantha_Rodrigo_2025.jpg?width=200",e:"St. Benedict's College, Colombo; SLMA; Indian Military Academy; KDU (MSc); NDU USA (MA)",j:"20 Jan 1989 (RI 31)",c:"CO 18 Field Regt Arty; Commander 663/661 Brigades; Commander 66 Div; Cmdt DSCSC; Commander SF Central; Cmdt SLAVF; Deputy CoS; CoS Army",a:"Led Operation Yukthiya; served as Cmdt DSCSC before becoming commander",w:"Led army Dec 2024–Jul 2026; oversaw security operations",d:"RSP",u:"Sri Lanka Artillery"},
{n:"24th",nm:"Gen Vikum Liyanage",rk:"General",t:"Jun 2022 – Dec 2024",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Vikum_Liyanage_in_New_Delhi.jpg?width=200",e:"Vijaya College Matale; SLMA; Pakistan Military Academy",j:"27 Oct 1986 (RI 26)",c:"CO 8 Gajaba Regt; Commander 215 Brigade; Div Commander 21 Div; Commander SF West/Central; Cmdt SLAVF; CoS Army",a:"Second from Gajaba Regiment to become commander; led during economic crisis",w:"Led army during 2022-2024 economic crisis and political transitions",d:"RWP (x2 bars), RSP (bar), Desha Puthra Sammanaya",u:"Gajaba Regiment"},
{n:"23rd",nm:"Gen Shavendra Silva",rk:"General",t:"Aug 2019 – May 2022",p:"https://www.defence.lk/upload/profile/Comd_of_the_Army_2019.jpg",e:"Vijaya College Matale; SLMA; DSSC; NDC India; Harvard University; Marine Corps War College USA",j:"5 Mar 1984 (19th OCI)",c:"CO 8th/1st Bn Gajaba Regt; Brigade Cmdr Air Mobile; GOC 58 Div; Dir of Ops; Dep PR to UN; Adj Gen; CoS; CoDS",a:"GOC of elite 58 Div in Eelam War IV; most decorated soldier (20+ medals); youngest Maj Gen; led COVID-19 response via NOCPCO",w:"Led army 2019-2022; oversaw COVID-19 pandemic response",d:"WWV, RWP, RSP, VSV, USP, Desha Putra Sammanaya",u:"Gajaba Regiment",co:"US travel ban Feb 2020; UK sanctions Mar 2025"},
{n:"22nd",nm:"Gen Mahesh Senanayake",rk:"General",t:"Jul 2017 – Aug 2019",p:"https://www.army.lk/archive_upload/pressbreifing_1.jpg",e:"Ananda College; JNU (BSc Civil Eng); SLMA; US Army CGSC",j:"16 Oct 1981 (16th OCI)",c:"CO 3 SF Regt; Brigade Cmdr SF Brigade; GOC 52 Div; Commander SF Jaffna; CoS Army",a:"Veteran of all 4 phases of civil war; US CGSC Intl Hall of Fame (2021); contested 2019 presidential election (4th)",w:"Led army during 2018 anti-Muslim riots and 2019 Easter bombings",d:"RWP (bar), RSP (bar), VSV, USP",u:"Sri Lanka Engineers / SF"},
{n:"21st",nm:"Gen Crishantha de Silva",rk:"General",t:"Feb 2015 – Jul 2017",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/160727-N-GR718-083_(28595582865)_(cropped).jpg?width=400",e:"Royal College; SLMA; Staff College Camberley UK; Nanjing PLA College China; CME Pune India; NDC Pakistan; APCSS USA; MSc Indonesia",j:"Feb 1980 as officer cadet",c:"Cmdt DSCSC; Cmdt SLMA; Commander SLAVF; CoS Army; CoDS",a:"First engineer to become army commander; later HC to Bangladesh",w:"Led army during post-war period under Sirisena government",d:"RWP, USP",u:"Sri Lanka Engineers"},
{n:"20th",nm:"Gen Daya Ratnayake",rk:"General",t:"Aug 2013 – Feb 2015",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_20.png",e:"Maliyadeva College; SLMA; DSSC Bangladesh; NDU China; Intel School USA; Cranfield UK",j:"1980 as officer cadet",c:"CO 6th Bn SLLI; GOC 23 Div; Commr Gen Rehabilitation; CoS Army",a:"Most decorated to become commander; rehabilitated 12,000 ex-LTTE; Battle of Thoppigala",w:"Oversaw post-war army during Rajapaksa→Sirisena transition",d:"WWV, RWP (x4), RSP (x4), USP, Desha Puthra Padakkama",u:"Sri Lanka Light Infantry"},
{n:"19th",nm:"Lt Gen Jagath Jayasuriya",rk:"General",t:"Jul 2009 – Jul 2013",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Jagath_Jayasuriya.jpg?width=200",e:"Royal College; DSSC; Naval Postgrad School USA; NDC India; Univ of Madras (MSc)",j:"1978 as cadet; commissioned 23 Jan 1980",c:"Commander SF Wanni; CoS Army; CoDS",a:"Commanded SLA offensives in Wanni 2008-2009; 5 divs + 3 task forces (largest in SLA history); later Ambassador to Brazil",w:"Led army through post-war consolidation and restructuring",d:"VSV, USP, Desha Putra Sammanaya",u:"Sri Lanka Armoured Corps",co:"Accused of war crimes by ITJP 2017; UK sanctions Mar 2025"},
{n:"18th",nm:"FM Sarath Fonseka",rk:"Field Marshal",t:"Dec 2005 – Jul 2009",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Fonseka_Press_Conference.jpg?width=200",e:"Dharmasoka College; Ananda College; SLMA; DSSC Bangladesh; RCDS London",j:"5 Feb 1970 as cadet officer",c:"CO 4th SLLI; Commander SF Jaffna; Commander SF Wanni; Commander of the Army; CoDS",a:"Masterminded strategy ending 26-year civil war; survived LTTE suicide bomb Apr 2006; first serving cmdr promoted to full Gen; Field Marshal 2015 (first Sri Lankan)",w:"Led final phase of Eelam War IV; transformed army offensive posture; combined naval/air power with land ops",d:"RWP, RSP, VSV, USP, Desha Putra Sammanaya",u:"Sri Lanka Sinha Regiment",co:"Arrested/court-martialed after 2010 election; imprisoned 2010-2012; pardoned 2015; Cabinet Minister 2016-2018"},
{n:"17th",nm:"Gen Shantha Kottegoda",rk:"General",t:"Jul 2004 – Dec 2005",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_17.png",j:"Joined Sri Lanka Army",c:"Commander of the Army",a:"Managed army during fragile ceasefire before Eelam War IV",w:"Commanded during transition period before resumption of hostilities",d:"WWV, RWP, RSP, VSV, USP, VSP",u:"Sri Lanka Light Infantry"},
{n:"16th",nm:"Gen Lionel Balagalle",rk:"General",t:"Aug 2000 – Jun 2004",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_16.png",j:"Joined Sri Lanka Army",c:"Commander of the Army; Chief of Defence Staff",a:"Led army during 2001 ceasefire period; managed peace talks",w:"Oversaw army during ceasefire agreement and peace negotiations",d:"RWP, RSP, VSV, USP, VSP",u:"Sri Lanka Artillery"},
{n:"15th",nm:"Gen Srilal Weerasooriya",rk:"General",t:"Dec 1998 – Aug 2000",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_15.png",j:"Joined Sri Lanka Army",c:"Commander of the Army",a:"Led army when Elephant Pass fell to LTTE",w:"Managed army during LTTE major offensives",d:"RWP, RSP, VSV, USP",u:"Sri Lanka Artillery"},
{n:"14th",nm:"Gen Rohan de S. Daluwatte",rk:"General",t:"May 1996 – Dec 1998",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_14.png",j:"Joined Sri Lanka Army",c:"Commander of the Army",a:"Led Operation Jayasikurui against LTTE",w:"Continued major offensive operations against LTTE in the north",d:"RWP, RSP, VSV, USP",u:"Sri Lanka Armoured Corps"},
{n:"13th",nm:"Gen Gerry H. de Silva",rk:"General",t:"Jan 1994 – Apr 1996",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_13.png",e:"Royal College; SLMA",j:"Joined Sri Lanka Army",c:"Commander of the Army",a:"Led Operation Riviresa (recapture of Jaffna)",w:"Oversaw major operations including recapture of Jaffna from LTTE",d:"RWP, VSV, USP",u:"Gemunu Watch"},
{n:"12th",nm:"Gen Cecil Waidyaratne",rk:"General",t:"Nov 1991 – Dec 1993",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_12.png",e:"Royal College; Sandhurst",j:"Joined Sri Lanka Army",c:"Commander of the Army",a:"Led army during civil war escalation including Jaffna operations",w:"Oversaw military operations during civil war escalation",d:"VSV",u:"Sri Lanka Armoured Corps"},
{n:"11th",nm:"Gen Hamilton Wanasinghe",rk:"General",t:"Aug 1988 – Nov 1991",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_11.png",e:"Royal College; Sandhurst",j:"Joined Ceylon Army",c:"Commander of the Army; Chief of Defence Staff",a:"First cmdr customarily promoted to full General; concluded JVP Insurrection",w:"Oversaw conclusion of 1987-89 JVP Insurrection",d:"VSV",u:"Sri Lanka Artillery"},
{n:"10th",nm:"Gen Nalin Seneviratne",rk:"General",t:"Feb 1985 – Aug 1988",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_10.png",e:"Royal College; Sandhurst",j:"Joined Ceylon Army",c:"Commander of the Army",a:"Led army during IPKF period and JVP Insurrection",w:"Oversaw operations during IPKF presence and JVP insurrection",d:"VSV",u:"Sri Lanka Engineers"},
{n:"9th",nm:"Gen Tissa Weeratunga",rk:"General",t:"Oct 1981 – Feb 1985",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_9.png",e:"Royal College; Sandhurst",j:"Joined Ceylon Army",c:"Commander of the Army; GOC Joint Operations Command",a:"Second cmdr promoted to full General on retirement",w:"Led army during early Tamil militant conflict",d:"VSV",u:"Gemunu Watch"},
{n:"8th",nm:"Gen Denis Perera",rk:"General (Deshamanya)",t:"Oct 1977 – Oct 1981",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_8.png",e:"Royal College; Univ of Ceylon; Sandhurst",j:"Joined Ceylon Army",c:"Commander of the Army",a:"Led during early Tamil militant conflict; promoted full Gen 2007 (26yrs after retirement)",w:"Oversaw army response to emerging Tamil militancy",d:"VSV, Deshamanya",u:"Sri Lanka Engineers"},
{n:"7th",nm:"Gen Sepala Attygalle",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_7.png",rk:"General (Deshamanya)",t:"Oct 1967 – Oct 1977",e:"Royal College; Sandhurst",j:"Joined Ceylon Army",c:"Commander of the Army (longest—10yrs); Chief of Defence Staff",a:"Longest-serving cmdr; oversaw 1971 JVP Insurrection; first promoted full Gen on retirement",w:"Led army through 1971 JVP Insurrection—first major internal conflict",d:"LVO, Deshamanya",u:"Sri Lanka Armoured Corps"},
{n:"6th",nm:"Maj Gen Bertram Heyn",rk:"Major General",t:"Nov 1966 – Sep 1967",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/SLA-50.jpg?width=200",e:"Ceylon Light Infantry",j:"Joined Ceylon Army",c:"Commander of the Army",a:"Deshabandu national honour; WWII service",w:"Led army during post-1962 coup normalization",d:"WWII service medals",u:"Ceylon Light Infantry"},
{n:"5th",nm:"Maj Gen Richard Udugama",rk:"Major General",t:"Jan 1964 – Nov 1966",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_5.png",e:"Ceylon Light Infantry",j:"Joined Ceylon Army",c:"Commander of the Army",a:"Deshamanya national honour; MBE; resigned after 1966 unrest",w:"Led army during post-coup period and political instability",d:"MBE, WWII service medals",u:"Ceylon Light Infantry"},
{n:"4th",nm:"Maj Gen H.W.G. Wijeyekoon",rk:"Major General",t:"Jan 1960 – Dec 1963",p:"https://www.army.lk/themes/custom/web_tailwind/images/img/past_comd/Thumb_4.png",e:"Ceylon Light Infantry; Sandhurst",j:"Joined Ceylon Army",c:"Commander of the Army",a:"OBE; ED; oversaw army during early post-independence era",w:"Led army during peacetime consolidation",d:"OBE, ED",u:"Ceylon Light Infantry"},
{n:"3rd",nm:"Maj Gen Anton Muttukumaru",rk:"Major General",t:"Feb 1955 – Dec 1959",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/General_Anton_Muttukumaru.jpg?width=200",e:"Royal College Colombo; Royal Military Academy Sandhurst",j:"Joined the Ceylon Defence Force volunteers",c:"Commander of the Ceylon Army",a:"First Ceylonese Commander of the Army; first internal security operation (Operation Monty) during his tenure",w:"Oversaw the army's first internal security operations",d:"OBE, ED",u:"Ceylon Light Infantry"},
{n:"2nd",nm:"Brig Sir Francis Reid",rk:"Brigadier",t:"May 1952 – Feb 1955",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Reid_Francis_Smith.jpg?width=200",e:"Royal Artillery",j:"Appointed from British Army",c:"Commander of the Ceylon Army",a:"Continued development of the Ceylon Army",w:"Continued building the army's capabilities and structure",d:"CBE",u:"Royal Artillery"},
{n:"1st",nm:"Brig Roderick Sinclair",rk:"Brigadier",t:"Oct 1949 – May 1952",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Brigadier_Sinclair_The_Earl_of_Caithness.jpg?width=200",e:"Gordon Highlanders; British military education",j:"First Commander of the Ceylon Army, appointed from British Army",c:"Commandant of the Ceylon Army",a:"First Commander of the Ceylon Army; established the foundation of the army",w:"Oversaw the initial formation of the Ceylon Army from the Ceylon Defence Force",d:"CBE, DSO",u:"Gordon Highlanders"}
],
navy:[
{n:"27th",nm:"VAdm Damian Fernando",rk:"Vice Admiral",t:"Jul 2026 – Present",p:"https://www.navy.lk/assets/images/commander/commander-of-the-navy.webp",e:"St. Joseph Vaz College, Wennapuwa; NMA; INS Dronacharya India; Naval Gun Maint Eng Course China; RCDS UK; MSc Mgt (DS) KDU; MA Intl Security & Strategy King's College London; APCSS Hawaii; USNWC CFMCC Course",j:"12 Sep 1991 (21st intake); commissioned 12 Sep 1993 (Highest Aggregate Technical + Best Marksman)",c:"Chief of Staff (2024); Gunnery & Missiles specialist; hosted missile capability intro to fleet; Defence Attaché course BIDTI",a:"First in order of merit SLT Technical Course; Best All-Round Officer INS Dronacharya; AFNI; JP (Whole Island)",w:"Current commander—assumed office 1 Jul 2026",d:"RSP, USP, rcds"},
{n:"26th",nm:"Adm Kanchana Banagoda",rk:"Admiral",t:"Jan 2025 – Jun 2026",p:"https://www.navy.lk/assets/images/commander/former-commanders/adm-kanchana.banagoda.webp",e:"S. Thomas' College; NMA; BRNC Dartmouth UK; MBA HRM; M Maritime Policy Wollongong; NDC",j:"15 Sep 1989 (19th intake)",c:"Dir Naval Training; Commander SE/NC/N/N/E Naval Areas; Chief of Staff",a:"ASW specialist; led Navy into Combined Maritime Forces",w:"Led navy Jan 2025–Jun 2026",d:"RSP, USP"},
{n:"25th",nm:"Adm Priyantha Perera",rk:"Admiral",t:"Dec 2022 – Dec 2024",p:"https://www.navy.lk/assets/images/commander/former-commanders/adm-uvmp-perera.jpg",e:"Royal College; NMA; Three Master's degrees; NDU",j:"1987 (5th intake)",c:"Chief of Staff; Commander of the Navy",a:"Three-time RSP recipient; shaped Naval Strategy 2030; first sea-kayak circumnavigation",w:"Shaped Naval Strategy 2030; modernized fleet",d:"RSP***, USP, NDU, PSC"},
{n:"24th",nm:"Adm Nishantha Ulugetenne",rk:"Admiral",t:"Jul 2020 – Dec 2022",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-dns-ulugethanne.jpg",e:"Royal College; MA Defence Studies (King's College London); Maritime Policy (Wollongong); MPhil (Madras)",j:"1985",c:"Commander W/S Naval Areas; Dir Naval Intelligence; CoS; Ambassador to Cuba",a:"Intelligence specialist; Ambassador to Cuba",w:"Led fleet modernization; expanded naval intelligence",d:"RSP and Bar, VSV, USP",co:"Arrested Jul 2025 for 2010 disappearance case"},
{n:"23th",nm:"Adm Piyal De Silva",rk:"Admiral",t:"Jan 2019 – Jul 2020",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-kkvph-de-silva.jpg",e:"Dharmasoka College; NMA; MBA HRM; MDef&SS; NDC China",j:"1984 (12th intake)",c:"Commander E/S/NW/N Naval Areas; FOC Fleet; DG Ops; CoS; Ambassador to Afghanistan",a:"National basketball player; Best Sportsman of Navy twice; deep sea salvage expert",w:"Led navy during COVID-19 and 2019 Easter attacks aftermath",d:"WWV & Bar, RWP, RSP, VSV, USP"},
{n:"22th",nm:"Adm Sirimevan Ranasinghe",rk:"Admiral",t:"Oct 2017 – Dec 2018",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-ssranasingha.jpg",e:"Allied Officers' War Course NDU Islamabad; NDC New Delhi",j:"Sri Lanka Navy",c:"Initial CO SLNS Samudura; Commander S/W Naval Areas; Cmdt NMA; DG Ops; DG Coast Guard",a:"Commanded longest voyage in SLN history (USA to Colombo)",w:"Continued naval modernization and coastal defense",d:"WWV, RWP, USP"},
{n:"21th",nm:"Adm Travis Sinniah",rk:"Admiral",t:"Aug 2017 – Oct 2017",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-tjl-sinniah.jpg",e:"Defence Cooperation Course DISAM Ohio USA",j:"Sri Lanka Navy",c:"FOC Naval Fleet; Cmdt NMA; Commander Eastern Naval Area",a:"Served in all SLN Squadrons; shortest tenure; RSP x3",w:"Brief command—focused on operational continuity",d:"WWV, RWP, RSP (x3), USP"},
{n:"20th",nm:"Adm Ravindra Wijegunaratne",rk:"Admiral",t:"Jul 2015 – Aug 2017",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-rc-wijegunarathne.jpg",e:"Royal College; NMA; BRNC Dartmouth; BSc War Studies Karachi; MPhil Madras; NDC",j:"1 Nov 1980 (9th intake)",c:"Commander 4 Naval Commands; Dir Naval Ops; DG Coast Guard; CoDS; HC to Pakistan; MD CPC",a:"Best Intl Midshipman at BRNC; WV recipient; CDS 2017-2020",w:"Led navy post-war; expanded coast guard",d:"WV, RWP & Bar, RSP, VSV, USP, NI (M) Pakistan"},
{n:"19th",nm:"Adm Jayantha Perera",rk:"Admiral",t:"Jul 2014 – Jul 2015",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-jayantha-perera.jpg",e:"NMA; Gunnery School Kochi India; Naval Staff Course India; NDC Islamabad; MSc",j:"23 Aug 1978",c:"Chief of Staff; Commander of the Navy",a:"Gunnery specialist",w:"Continued operational readiness and fleet training",d:"RWP, VSV, USP, NDC, PSC"},
{n:"18th",nm:"Adm Jayanath Colombage",rk:"Admiral",t:"Sep 2012 – Jun 2014",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-jsk-colombage.jpg",e:"St. Sylvester's College; NMA (Sword of Honour); BRNC Dartmouth; MSc Madras; MA King's College London; PhD KDU; DSSC Wellington; RCDS UK",j:"1978 (7th intake)",c:"Commander E/N/W/NC Naval Areas; DG Ops (twice); Addl Secy to President; Secy MFA; Ambassador to Indonesia/ASEAN",a:"Authored 'Asymmetric Warfare at Sea'; Fellow of Nautical Institute; Guest Prof in China",w:"Expanded naval diplomatic reach and international cooperation",d:"RSP, VSV, USP, 5-Star Commendation"},
{n:"17th",nm:"Adm Somathilake Dissanayake",rk:"Admiral",t:"Jan 2011 – Sep 2012",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-dwas-dissanayake.jpg",e:"Mayurapada Central College; NMA; INS Venduruthy India; RN Intl Warfare Course; NDC; MPhil Madras; MDef&SS KDU",j:"1 Jun 1977",c:"Defence Adviser New Delhi; Commander Eastern Naval Area; CoS; Advisor to President",a:"Most decorated Naval Officer in 60-year history; led decisive Northern Naval Ops in final LTTE battle",w:"Led final naval ops against LTTE in Eelam War IV",d:"WV, RSP & Bar, VSV, USP, 5-Star Commendation"},
{n:"16th",nm:"Adm Thisara Samarasinghe",rk:"Admiral",t:"Jul 2009 – Jan 2011",p:"https://www.navy.lk/assets/images/commander/former-commanders/adm-tsg-samarasinghe.jpg",e:"Royal College; NMA (Sword of Honour); BRNC Dartmouth (Best Intl Midshipman); INS Venduruthy (1st in merit); US Naval War College; NDC New Delhi",j:"1974 (4th intake)",c:"Commander S/E/N Naval Areas; DG Naval Ops; CoS; HC to Australia",a:"Speaker at 19th Intl Seapower Symposium; organized Navy's 60th Anniversary",w:"Led post-war naval reconstruction and international engagement",d:"RSP, VSV, USP, 5 commendation letters"},
{n:"15th",nm:"Adm of the Fleet Wasantha Karannagoda",rk:"Admiral of the Fleet",t:"Sep 2005 – Jul 2009",p:"https://www.navy.lk/assets/images/commander/former-commanders/adm-wasantha-karannagoda-1.jpg",e:"Ananda College; NMA; MBA; MSc Defence Studies; MRIN; MNI; APCSS Hawaii; NDU Washington D.C.",j:"1 Aug 1971",c:"Commander 7th Surveillance Squadron; Commander 4 Naval Cmds (7 occasions); Advisor to President; Ambassador to Japan; Gov NW Province",a:"First naval officer with 4-star rank in active service; led operations in Eelam War IV",w:"Led navy during decisive final phase of civil war against LTTE",d:"RSP, VSV, USP",co:"Named in Navy 11 abduction case; arrested Jul 2026"},
{n:"14th",nm:"Adm Daya Sandagiri",rk:"Admiral",t:"Jan 2001 – Sep 2005",p:"https://www.navy.lk/assets/images/commander/former-commanders/admiral-dwk-sandagiri.jpg",e:"St. Mary's Maha Vidyalaya; Kegalu Vidyalaya; NMA (first batch 1969)",j:"14 Nov 1966",c:"Cmdt NMA; CoS; CoDS; Chancellor of KDU",a:"First naval officer as CoDS; strategic overhaul vs Sea Tigers",w:"Transformed naval strategy against Sea Tigers; expanded coastal surveillance",d:"RSP, VSV, USP, Purna Bhoomi Padakkama"},
{n:"13th",nm:"Adm H.C.A.C. Tissera",rk:"Admiral",t:"Jan 1997 – Dec 2000",p:"https://www.navy.lk/assets/images/commander/former-commanders/vadm-hcac-thisera.jpg",e:"Naval & Maritime Academy",j:"Royal Ceylon Navy officer",c:"Captain 1988; Commodore 1992; Cmdt Naval & Maritime Academy 1995; Chief of Staff; Commander of the Navy",a:"Promoted Vice Admiral on assumption of command; VSV recipient",w:"Led navy in late 1990s during Eelam War III",d:"VSV"},
{n:"12th",nm:"Adm D.A.M.R. Samarasekara",rk:"Admiral",t:"Nov 1992 – Jan 1997",p:"https://www.navy.lk/assets/images/commander/former-commanders/adm-damr-samarasekara.jpg",e:"Naval & Maritime Academy; Staff Course USA 1992",j:"Royal Ceylon Navy officer",c:"Commander of the Navy; Chief of Staff",a:"Rear Admiral 1992; Vice Admiral 1993 on command; Admiral on retirement",w:"Led navy after assassination of his predecessor; post-WW crisis period",d:"VSV"},
{n:"11th",nm:"Adm W.W.E.C. Fernando",rk:"Admiral",t:"Nov 1991 – Nov 1992",p:"https://www.navy.lk/assets/images/commander/former-commanders/adm-wwec-fernando.jpg",e:"Naval & Maritime Academy",j:"Royal Ceylon Navy officer",c:"Commander of the Navy",a:"Intensified war to cut LTTE MSR; assassinated by LTTE suicide bomber 16 Nov 1992; posthumously promoted Admiral",w:"Led navy during Eelam War II escalation",d:"Purna Bhoomi Padakkama, VSV"},
{n:"10th",nm:"Adm H.A. Silva",rk:"Admiral",t:"Nov 1986 – Oct 1991",p:"https://www.navy.lk/assets/images/commander/former-commanders/adm-ha-silva.jpg",e:"Naval & Maritime Academy",j:"Royal Ceylon Navy officer",c:"Commodore 1983; first Chief of Staff promoted Rear Admiral 1986; Commander of the Navy",a:"Vice Admiral on command; Admiral on retirement",w:"Led navy during early Eelam War and IPKF period",d:"VSV"},
{n:"9th",nm:"VAdm A.H.A. de Silva",rk:"Vice Admiral",t:"Jun 1983 – Oct 1986",p:"https://www.navy.lk/assets/images/commander/former-commanders/vadm-aha-de-silva.jpg",e:"Naval & Maritime Academy",j:"Royal Ceylon Navy officer",c:"Commander of the Navy; JOSSOP (Joint Services Special Ops Command)",a:"Also commanded Joint Services Special Operations Command; Ambassador to Cuba after retirement",w:"Led navy during early civil conflict escalation",d:"VSV"},
{n:"8th",nm:"RAdm A.W.H. Perera",rk:"Rear Admiral",t:"Jun 1979 – May 1983",p:"https://www.navy.lk/assets/images/commander/former-commanders/radm-awh-perera.jpg",e:"UK Gunnery Course 1958",j:"Commissioned Sub Lieutenant 1945; UN Military Observers team West Iran 1962",c:"Coordinating Officer Polonnaruwa 1972; Captain 1973; Commander of the Navy",a:"Rear Admiral on command; Ambassador to Kenya after retirement",w:"Led navy during transition to civil conflict; expanded fleet",d:"VSV"},
{n:"7th",nm:"RAdm D.B. Goonesekara",rk:"Rear Admiral",t:"Jun 1973 – May 1979",p:"https://www.navy.lk/assets/images/commander/former-commanders/radm-db-goonesekara.jpg",e:"Naval & Maritime Academy",j:"Royal Ceylon Navy officer",c:"Captain 1972; Commodore 1973; Rear Admiral on command",a:"Led navy through SRNS→SLN transition era",w:"Led navy during post-1971 normalization",d:"VSV"},
{n:"6th",nm:"RAdm D.V. Hunter",rk:"Rear Admiral",t:"Jul 1970 – May 1973",p:"https://www.navy.lk/assets/images/commander/former-commanders/radm-dv-hunter.jpg",e:"Pilotage training Madras 1963",j:"Enlisted CNVF/CRNVR 21 Oct 1938; PO 1941; commissioned Sub Lt 1942; Lt 1944",c:"Served on all CRNVR ships; MFV 185 Akyab Burma front 1944-45; CO Volunteer Naval Force 1965",a:"Commodore 1970; Rear Admiral at retirement 1973; WWII Star and Burma Star",w:"Led navy during 1971 JVP Insurrection response",d:"Star & Burma Star (WWII)"},
{n:"5th",nm:"RAdm R. Kadiragamar",rk:"Rear Admiral",t:"Nov 1960 – Jun 1970",p:"https://www.navy.lk/assets/images/commander/former-commanders/radm-r-kadiragamar.jpg",e:"Royal Naval training",j:"Royal Ceylon Navy officer",c:"Temporary Commodore 1960 (confirmed 1964); Working Director Port (Cargo) Corporation",a:"Longest-serving early commander; WWII Star and Burma Star",w:"Led navy through decade of development",d:"Star & Burma Star (WWII)"},
{n:"4th",nm:"RAdm G.R.M. de Mel",rk:"Rear Admiral",t:"Jul 1955 – Nov 1960",p:"https://www.navy.lk/assets/images/commander/former-commanders/radm-grm-de-mel.jpg",e:"Trained abroad as senior-most Ceylonese officer after Navy Act",j:"Royal Ceylon Navy officer",c:"Extra A.D.C. to the Queen 1954; Captain confirmed 1955; Commodore 1955; Rear Admiral 1959",a:"First Ceylonese to command after Navy Act; WWII medals",w:"Led navy during post-Navy Act modernization",d:"1939-45 Defence Medal, Star & Burma Star"},
{n:"3rd",nm:"Cmde P.M.B. Chavasse",rk:"Commodore",t:"Jun 1953 – Jul 1955",p:"https://www.navy.lk/assets/images/commander/former-commanders/cmde-pmb-chavasse.jpg",e:"Royal Navy",j:"Last Royal Navy loan officer appointed Captain of the Navy",c:"Captain of the Navy; promoted Commodore on departure",a:"Captain of the Navy during Queen's visit 1953",w:"Led navy during early Ceylonese naval development",d:"WWII service medals"},
{n:"2nd",nm:"Capt J.R.S. Brown",rk:"Captain",t:"Nov 1951 – Jun 1953",p:"https://www.navy.lk/assets/images/commander/former-commanders/capt-jrs-brown.jpg",e:"Royal Navy",j:"Royal Navy loan officer",c:"Captain of the Navy",a:"Served one-and-a-half years in Ceylon",w:"Succeeded Banks; short transitional command",d:"WWII service medals"},
{n:"1st",nm:"Capt W.E. Banks",rk:"Captain",t:"Dec 1950 – Nov 1951",p:"https://www.navy.lk/assets/images/commander/former-commanders/capt-we-banks.jpg",e:"Royal Navy",j:"Royal Navy loan officer; appointed first Captain of the Navy",c:"First Captain of the Navy 1950",a:"Founded the Royal Ceylon Navy as its first commander",w:"Established the Ceylon Navy (Royal Ceylon Navy) in 1950",d:"WWII service medals"}
],
airforce:[
{n:"20th",nm:"AVM Vasu Bandu Edirisinghe",rk:"Air Marshal",t:"Jan 2025 – Present",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Vasu_Bandu_Edirisinghe_in_June_2023.jpg?width=200",e:"St. Sylvester's College Kandy; SLAF Academy; courses Bangladesh/India/Alabama USA; NDC China",j:"1991 (24th Intake); commissioned 1993",c:"OC Training/Operations; CO No. 4/6/7 Helicopter Squadrons; Def Attaché Pakistan; DG Air Ops & Planning",a:"7,000+ helicopter hours; A2-rated helicopter instructor (RAF); qualified Instrument Rating Examiner; NVG expert",w:"Commander's Inspection 2025; Exercise Pacific Angel 2025 with US PACAF; rightsizing and modernization",d:"WWV, RWP, RSP & 3 Bars, USP",u:"No. 2 & 8 Squadron SLAF"},
{n:"19th",nm:"ACM Udeni Rajapaksa",rk:"Air Chief Marshal",t:"Jun 2023 – Jan 2025",p:"https://www.airforce.lk/images/other/19th_cmdr.png",e:"Parakrama Vidyalaya; Bandaranaike College; KDU; Air Univ USA (MSc); King's College London (MA); RCDS London",j:"1988; commissioned 1990—first KDU graduate to become Commander",c:"CO No. 2 Heavy Transport Sqn; Base Cdr Vavuniya/Katunayake; Cmdt SLAF Academy; Dir Air Ops; CoS; Def Counsellor Russia",a:"First KDU grad as Commander; ejected from Pucará 1997; 7,000+ hrs on 10 aircraft; COVID-19 response at Katunayake",w:"Modernization; Air Tattoo 2024; UN peacekeeping",d:"RWP & 2 Bars, RSP & 2 Bars, VSV, USP",u:"No. 2 & 8 Squadron SLAF"},
{n:"18th",nm:"ACM Sudarshana Pathirana",rk:"Air Chief Marshal",t:"Nov 2020 – Jun 2023",p:"https://www.airforce.lk/images/other/18th_cmdr.png",e:"Dharmaraja College Kandy; PAF Academy Risalpur Pakistan; KDU; Air Univ USA; Univ of Madras; NDC India",j:"2 Jul 1985; commissioned 2 Jan 1987",c:"First supersonic pilot batch; CO No. 5/10/12 Fighter Sqn; Cmdt SLAF Academy; Base Cdr Katunayake/Ratmalana; Dir Air Ops; CoS",a:"First SL supersonic pilots; commanded No. 10 Sqn with Kfir jets; 3,500+ hrs; 8 gallantry medals; downsized SLAF 35K→30K; US$6M UN missions; Ambassador to Nepal",w:"Post-war downsizing and modernization; UN deployments",d:"WWV & Bar (x2), RWP & Bar (x2), RSP & 3 Bars, VSV, USP",u:"No. 5 & 10 Squadron SLAF",co:"War crimes accusations from Tamil groups; recalled from Nepal 2024"},
{n:"17th",nm:"ACM Sumangala Dias",rk:"Air Chief Marshal",t:"May 2019 – Nov 2020",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Sumangala_Dias_PACAF_1-_portrait.jpg?width=200",e:"SLAF Academy China Bay; various courses",j:"12 Dec 1984 (13th Intake); commissioned 15 Aug 1986",c:"CO No. 6 Squadron; various base commands; Dir Air Ops; CoS",a:"Led SLAF during COVID-19 pandemic response; managed operations during political instability",w:"Managed SLAF during COVID-19 and 2019 Easter attacks aftermath",d:"RWP, RSP, VSV, USP",u:"No. 6 Squadron SLAF"},
{n:"16th",nm:"ACM Kapila Jayampathy",rk:"Air Chief Marshal",t:"Sep 2016 – May 2019",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Kapila_Jayampathy,_2017_(cropped).jpg?width=200",e:"SLAF Academy China Bay; various courses",j:"5 Mar 1982 (10th Intake)",c:"Commanded No. 4 Squadron; various base and staff appointments; CoS",a:"Extensive combat and VVIP flying experience",w:"Continued post-war development and modernization",d:"WWV, RWP, RSP",u:"No. 4 Squadron SLAF"},
{n:"15th",nm:"ACM Gagan Bulathsinghala",rk:"Air Chief Marshal",t:"Jun 2015 – Sep 2016",p:"https://www.airforce.lk/uploads/15th_sri_lanka_air_force_commander.jpg",e:"Nalanda College; Air Univ Alabama USA; NDC New Delhi; MPhil Madras; MSc KDU",j:"12 Feb 1981; commissioned 8 Apr 1983",c:"Founding CO No. 6 Helicopter Sqn; longest-serving CO No. 4 VIP Sqn; Base Cdr China Bay; Dir Ops; Dir Air Ops; CoS",a:"VVIP pilot 4,500+ hrs; flew 4 presidents; hit by RPG on Bell 412 (1986) but landed safely; founding CO No. 6 Sqn; Ambassador to Afghanistan",w:"Post-war transition; pursued JF-17 Thunder acquisition",d:"RWP, RSP, VSV, USP, NDC, PSC",u:"No. 4 Squadron SLAF",co:"Corruption allegations re helicopter supply contract (2015)"},
{n:"14th",nm:"ACM Kolitha Gunathilake",rk:"Air Chief Marshal",t:"Feb 2014 – Jun 2015",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Air_Chief_Marshal_Kolitha_Aravinda_Gunatilleke.jpg?width=200",e:"S. Thomas' Bandarawela; Royal College; KDU (MSc x2); Cmd & Staff College Pakistan; Joint Air Warfare College India; Air Univ; NDC",j:"1980 (8th Intake); commissioned Apr 1982",c:"CO No. 1 FTW; CO No. 2 Transport Sqn; Base Cdr China Bay/Katunayake; Dir Training; Dir Air Ops; CoS",a:"Flew SF.260 and Pucará in ground attack vs LTTE; qualified flying instructor; CDS after command (2015-2017); 37-year career",w:"Post-war modernization; international cooperation",d:"RWP & Bar, RSP, VSV, USP, NDC, PSC, QFI",u:"No. 2 Squadron SLAF"},
{n:"13th",nm:"ACM Harsha Abeywickrama",rk:"Air Chief Marshal",t:"Feb 2011 – Feb 2014",p:"https://en.wikipedia.org/wiki/Special:Redirect/file/Harsha_Abeywickrama.jpg?width=200",e:"Richmond College; Royal College; King's College London (MA); KDU (MSc); RCDS; Air Univ",j:"19 Apr 1980; commissioned 1982",c:"First CO No. 5 'Jet' Squadron (re-established 1991); first SL pilot in F-7 (1991) and Kfir (1996); CO SLAF Palaly; Base Cdr China Bay/Anuradhapura/Ratmalana; Dir Air Ops (2006-09); Deputy CoS",a:"Pioneered supersonic flight in F-7; created Battle Management Centre fusing UAVs/radar; spearheaded air ops concluding civil war 2009; Chairman Bank of Ceylon; Chairman Airport & Aviation Services",w:"Transitioned SLAF from wartime to post-conflict; revenue through Heli-Tours",d:"RWP & Bar (x2), RSP, VSV, USP, RCDS, PSC, QFI",u:"No. 5 Squadron SLAF"},
{n:"12th",nm:"MRAFL Roshan Goonetileke",rk:"Marshal of the SLAF",t:"Jun 2006 – Feb 2011",p:"https://www.airforce.lk/uploads/past_cmdrs/12.jpg",e:"St. Peter's College; Air Univ Alabama USA (1994); NDC Pakistan (2001)",j:"13 Jan 1978; commissioned 24 Aug 1979",c:"CO No. 3 Maritime Sqn; CO No. 4 Sqn; Base Cdr; Dir Ops; CoS",a:"Son of 5th Commander; brother KIA 1995; first Marshal of SLAF (2019); commanded during final war phase; Chairman Civil Aviation; Governor Western Province",w:"Led SLAF during final Eelam War IV and defeat of LTTE (May 2009)",d:"RWP & Bar (x2), VSV, USP, NDC, PSC; Marshal of SLAF rank",u:"No. 4 Squadron SLAF",co:"MiG deal scrutiny; war operations allegations"},
{n:"11th",nm:"ACM Donald Perera",rk:"Air Chief Marshal",t:"Jul 2002 – Jun 2006",p:"https://www.airforce.lk/uploads/air_chief_marshal_g_d_perera.jpg",e:"S. Thomas' College; SLAF Academy (Intake 1); Air Univ 1990; NDC New Delhi 1998",j:"12 Jan 1972 (Intake 1); commissioned 19 Oct 1973",c:"Cmdt FTW China Bay; CO No. 2 Sqn; Base Cdr Katunayake; Zonal Cdr West/East; Acting Dir Ops; CoS (Dec 1998)",a:"7,500+ flying hours on transports; served as CoDS during final civil war; Ambassador to Israel",w:"Led SLAF during post-peace process and start of Eelam War IV",d:"VSV, USP, NDC, PSC",u:"No. 2 Squadron SLAF"},
{n:"10th",nm:"ACM Jayalath Weerakkody",rk:"Air Chief Marshal",t:"Mar 1998 – Jul 2002",p:"https://www.airforce.lk/uploads/air_chief_marshal_j_weerakkody.gif",e:"Dharmashoka College; SLAF Academy (Intake 1); Air Admin College Coimbatore; Air Command Staff College Maxwell AFB; NDC New Delhi",j:"12 Jan 1972 (Intake 1)",c:"CO No. 4 Sqn; CO No. 2 Sqn; Base Cdr Anuradhapura; Northern Zonal Cdr; Dir Ops; CoS",a:"Acquired MiG-27; established JC&SC at China Bay (1999); NCO School (2000); three-time RWP",w:"Modernized trainer fleet; acquired MiG-27s; established training institutions",d:"RWP (x3), VSV, USP, NDC, PSC, QFI",u:"No. 2 & 4 Squadron SLAF"},
{n:"9th",nm:"ACM Oliver Ranasinghe",rk:"Air Chief Marshal",t:"Feb 1994 – Mar 1998",p:"https://www.airforce.lk/uploads/air_marshal_oliver_ranasinghe.jpg",e:"Dharmapala College; Air Staff College Maxwell AFB USA; NDC New Delhi; Senior Mgmt Course Monterey",j:"7 Feb 1968 as Sergeant Pilot",c:"CO No. 4 Sqn; first Base Cdr SLAF Anuradhapura; Dir Ops; CoS",a:"Deployed Kfir/Mi-24/AN-32B/UAVs; SLAF won National Quality Award 1995; first South Asian AF to deploy UAVs (1995); 1985 overnight Jaffna Fort airlift of 250 troops",w:"Led SLAF during Eelam War III; modernized fleet; Operation Riviresa",d:"RWP, VSV, USP, NDC, PSC",u:"No. 4 Squadron SLAF",co:"Scrutiny over aircraft losses (17 lost 1995-97)"},
{n:"8th",nm:"ACM Terry Gunawardena",rk:"Air Chief Marshal",t:"Aug 1990 – Feb 1994",p:"https://www.airforce.lk/uploads/air_chief_marshal_m.j.t._de_s._gunawardena.jpg",e:"Wesley College; RAF Staff College Bracknell UK; NDC New Delhi",j:"31 Dec 1959; commissioned pilot officer 1961",c:"CO No. 2 Sqn; Cmdt SLAF Academy China Bay; CoS (Mar 1986)",a:"Revived fighter capability; acquired F-7/Pucará/Mi-17; introduced zonal command structure; pioneered jet ops",w:"Led SLAF during Eelam War II; expanded fighter capabilities",d:"VSV, NDC, PSC",u:"No. 2 Squadron SLAF"},
{n:"7th",nm:"ACM Walter Fernando",rk:"Air Chief Marshal",t:"May 1985 – Jul 1990",p:"https://www.airforce.lk/uploads/air_chief_marshal_a.w._fernando.jpg",e:"Ground combat training Diyatalawa; Flight Training Katunayake",j:"Jan 1953 as Cadet (2nd batch locally trained)",c:"Extensive flying career; squadron pilot; various command positions",a:"One of early locally trained pilots; served during civil war escalation",w:"Led SLAF during civil war escalation and JVP Insurrection",d:"VSV, NDC, PSC",u:"No. 4 Squadron SLAF"},
{n:"6th",nm:"ACM Dick Perera",rk:"Air Chief Marshal",t:"May 1981 – Apr 1985",p:"https://www.airforce.lk/uploads/air_vice_marshal_dick_cuthbert_perera.jpg",e:"St Benedict's College; joined 21 Sep 1951",j:"21 Sep 1951; trained on Chipmunk and Balliol",c:"Chief of Staff under ACM Goonetileke; airfield reclamation programmes",a:"Ideal successor; continued airfield rehabilitation",w:"Continued modernization and development",d:"VSV, NDC, PSC",u:"No. 2 Squadron SLAF"},
{n:"5th",nm:"ACM Harry Goonatilake",rk:"Air Chief Marshal",t:"Nov 1976 – Apr 1981",p:"https://www.airforce.lk/uploads/air_commodore_harry_hoonetileke.gif",e:"Royal College Colombo",j:"1951 as Flight Cadet (1st batch locally trained)",c:"Rose through ranks over 25+ years",a:"Part of first batch of locally trained pilots",w:"Continued SLAF development during post-independence era",d:"USP",u:"No. 2 Squadron SLAF"},
{n:"4th",nm:"ACM Paddy Mendis",rk:"Air Chief Marshal",t:"Jan 1971 – Nov 1976",p:"https://www.airforce.lk/uploads/air_chief_marshal_p_h_mendis.gif",e:"RAF College Cranwell (No. 61 entry); UK training",j:"Aug 1951 (5th person to join RCyAF)",c:"Various flying and command positions",a:"Youngest Commander of any armed service in Ceylon (age 38); commanded during 1971 JVP Insurrection; deployed Jet Provosts for combat within 3 days",w:"Led SLAF during 1971 JVP Insurrection; transformed RCyAF→SLAF (1972)",d:"IDC, PSC, FBIM, QFI; Deshamanya title",u:"No. 2 & 5 Squadron SLAF"},
{n:"3th",nm:"AVM Rohan Amarasekera",rk:"Air Vice Marshal",t:"Nov 1962 – Dec 1970",p:"https://www.airforce.lk/uploads/air_vice_marshal_e.r.amarasekara.gif",e:"RAF Bomber Command WWII veteran",j:"Returned to Ceylon 1951 as founding RCyAF member",c:"Navigator in RAF Bomber Command; one of first RCyAF officers",a:"WWII hero; DFC & Bar for gallantry in RAF Bomber Command",w:"Led air force during development and modernization period",d:"DFC & Bar",u:"No. 2 Squadron SLAF"},
{n:"2nd",nm:"AVM J.L. Barker",rk:"Air Vice Marshal",t:"1958 – 1962",p:"https://www.airforce.lk/uploads/air_vice_marshal_j.l.barker_commander_of_the_air_force_1958-1962.gif",e:"Royal Air Force",j:"RAF officer seconded to RCyAF",c:"Commander of the Air Force 1958-1962",a:"Developed RCyAF capabilities under RAF heritage",w:"Led air force during 1958 riots and early development",d:"WWII service medals",u:"No. 2 Squadron SLAF"},
{n:"1st",nm:"G/Cpt G.C. Bladon",rk:"Group Captain",t:"1951 – 1958",p:"https://www.airforce.lk/uploads/air_commodore_gc_bladon.jpg",e:"Royal Air Force",j:"RAF officer; founded the Royal Ceylon Air Force 2 Mar 1951",c:"First Commander of RCyAF; built first squadrons at Katunayake and China Bay",a:"Founded the Royal Ceylon Air Force on 2 March 1951",w:"Established RCyAF and its early squadrons",d:"WWII service medals",u:"No. 2 Squadron SLAF"}
],
police:[
{n:"37th",nm:"Priyantha Weerasooriya",rk:"Inspector General",t:"Aug 2025 – Present",p:"https://www.police.lk/wp-content/uploads/2025/08/IGP_Priyantha_weerasooriya.png",e:"Univ of Colombo (LLB); Sri Lanka Law College (Attorney-at-Law); Univ of Colombo (MBA HRM)",j:"Joined as Police Constable 20 May 1988; SI 1992; ASP direct entry 1999; first officer to rise from constable to IGP",c:"STF, traffic, crime divisions; SP 2007; SSP 2012; DIG 2016; SDIG 2020; SDIG North Central Province; Acting IGP Sep 2024",a:"37th IGP; UN peacekeeping East Timor & Haiti 2008-2011; 10 IGP commendations",w:"Current IGP—assumed duties 13 Aug 2025",d:"—"},
{n:"36th",nm:"Deshabandu Tennakoon",rk:"Inspector General",t:"Feb 2024 – Aug 2025",p:"https://www.police.lk/wp-content/uploads/2025/08/deshabandu-thennakon.png",e:"—",j:"Senior police officer; appointed Acting IGP 29 Nov 2023; confirmed 26 Feb 2024",c:"Career in Sri Lanka Police; SDIG",a:"Formally confirmed IGP Feb 2024; first IGP removed by Parliament resolution",w:"Suspended by Supreme Court 24 Jul 2024; removed from office 5 Aug 2025",d:"—",co:"Suspension and removal followed the 2019 Easter attacks investigations"},
{n:"35th",nm:"C.D. Wickramaratne",rk:"Inspector General",t:"Nov 2020 – Nov 2023",p:"https://www.police.lk/wp-content/uploads/2024/10/01-199x249x0x0x199x249x1701340295.jpg",e:"—",j:"Senior police officer; Acting IGP from 29 Apr 2019",c:"Senior DIG; Acting IGP during Easter attacks aftermath",a:"Permanent IGP 27 Nov 2020; tenure extended twice before Constitutional Council rejection",w:"Led police through post-Easter attacks reforms and COVID-19 pandemic",d:"—"},
{n:"34th",nm:"Pujith Jayasundara",rk:"Inspector General",t:"Apr 2016 – Mar 2020",p:"img/pujith_jayasundara.jpg",e:"—",j:"Career police officer; appointed 34th IGP",c:"Career in Sri Lanka Police; senior appointments",a:"IGP during 2019 Easter bombings",w:"Sent on compulsory leave 26 Apr 2019 over Easter attacks; formally retired 14 Mar 2020",d:"—",co:"Failed to act on intelligence warnings before Easter attacks"},
{n:"33rd",nm:"N.K. Illangakoon",rk:"Inspector General",t:"Jul 2011 – Apr 2016",p:"https://www.police.lk/wp-content/uploads/2024/10/03-199x249x0x1x199x247x1701340296.jpg",e:"—",j:"Career police officer; appointed 33rd IGP",c:"Senior police appointments including DIG and SDIG",a:"Served five-year term to retirement",w:"Led police during post-civil war period",d:"—"},
{n:"32nd",nm:"Mahinda Balasuriya",rk:"Inspector General",t:"Nov 2009 – Jun 2011",p:"https://www.police.lk/wp-content/uploads/2024/10/04-199x249x0x0x199x249x1701340297.jpg",e:"—",j:"Career police officer; appointed 32nd IGP",c:"Career in Sri Lanka Police",a:"Led police during end of civil war period",w:"Led police through final phase of Eelam War IV and aftermath",d:"—"},
{n:"31st",nm:"Jayantha Wickramarathne",rk:"Inspector General",t:"Jul 2008 – Nov 2009",p:"https://www.police.lk/wp-content/uploads/2024/10/06-199x249x0x0x199x249x1701340298.jpg",e:"—",j:"Career police officer; appointed 31st IGP",c:"Career in Sri Lanka Police",a:"Served during final civil war offensive",w:"Led police during final stages of civil war",d:"—"},
{n:"30th",nm:"Victor Perera",rk:"Inspector General",t:"Oct 2006 – Jun 2008",p:"https://www.police.lk/wp-content/uploads/2024/10/05-198x248x0x0x198x248x1701340297.jpg",e:"—",j:"Career police officer; appointed 30th IGP",c:"Career in Sri Lanka Police",a:"Served during Eelam War IV beginning",w:"Led police during escalation of civil war",d:"—"},
{n:"29th",nm:"Chandra Fernando",rk:"Inspector General",t:"Oct 2004 – Oct 2006",p:"https://www.police.lk/wp-content/uploads/2024/10/07-198x248x0x0x198x248x1701340298.jpg",e:"—",j:"Career police officer; appointed 29th IGP",c:"Career in Sri Lanka Police",a:"Served during post-tsunami recovery period",w:"Led police during 2004 tsunami aftermath",d:"—"},
{n:"28th",nm:"Indra de Silva",rk:"Inspector General",t:"Dec 2003 – Sep 2004",p:"https://www.police.lk/wp-content/uploads/2024/10/08-198x248x0x0x198x248x1701340299.jpg",e:"—",j:"Career police officer; appointed 28th IGP",c:"Career in Sri Lanka Police",a:"Short tenure as IGP",w:"Led police during political transition",d:"—"},
{n:"27th",nm:"T.E. Anandaraja",rk:"Inspector General",t:"Oct 2002 – Oct 2003",p:"https://www.police.lk/wp-content/uploads/2024/10/09-198x248x0x0x198x248x1701340299.jpg",e:"—",j:"Career police officer; appointed 27th IGP",c:"Career in Sri Lanka Police",a:"Served during Norwegian-brokered ceasefire talks",w:"Led police during ceasefire negotiations period",d:"—"},
{n:"26th",nm:"Lakdasa Kodituwakku",rk:"Inspector General",t:"Sep 1998 – Aug 2002",p:"https://www.police.lk/wp-content/uploads/2024/10/10-198x248x0x0x198x248x1701340300.jpg",e:"—",j:"Career police officer; appointed 26th IGP",c:"Career in Sri Lanka Police",a:"Served through major civil war operations",w:"Led police during intense civil war period",d:"—"},
{n:"25th",nm:"Wickremasinghe Rajaguru",rk:"Inspector General",t:"Jul 1995 – Aug 1998",p:"https://www.police.lk/wp-content/uploads/2024/10/11-198x248x0x0x198x248x1701340300.jpg",e:"—",j:"Career police officer; appointed 25th IGP",c:"Career in Sri Lanka Police",a:"Served during period of major LTTE operations",w:"Led police during civil war escalation",d:"—"},
{n:"24th",nm:"Frank de Silva",rk:"Inspector General",t:"Nov 1993 – Jul 1995",p:"https://www.police.lk/wp-content/uploads/2024/10/12-198x248x0x0x198x248x1701340301.jpg",e:"—",j:"Career police officer; appointed 24th IGP",c:"Career in Sri Lanka Police",a:"Served during Eelam War III",w:"Led police during major LTTE offensives",d:"—"},
{n:"23rd",nm:"Ernest Perera",rk:"Inspector General",t:"Aug 1988 – Nov 1993",p:"https://www.police.lk/wp-content/uploads/2024/10/13-198x248x0x0x198x248x1701340301.jpg",e:"—",j:"Career police officer; appointed 23rd IGP",c:"Career in Sri Lanka Police",a:"Served during JVP Insurrection II and Eelam War I/II",w:"Led police during JVP Insurrection and civil war beginnings",d:"—"},
{n:"22nd",nm:"Cyril Herath",rk:"Inspector General",t:"Dec 1985 – Jul 1988",p:"https://www.police.lk/wp-content/uploads/2024/10/14-198x248x0x0x198x248x1701340302.jpg",e:"—",j:"Career police officer; appointed 22nd IGP",c:"Career in Sri Lanka Police",a:"Served during ethnic conflict escalation",w:"Led police during early civil conflict period",d:"—"},
{n:"21st",nm:"Herbert Weerasinghe",rk:"Inspector General",t:"Apr 1985 – Dec 1985",p:"https://www.police.lk/wp-content/uploads/2024/10/15-198x248x0x0x198x248x1701340303.jpg",e:"—",j:"Career police officer; appointed 21st IGP",c:"Career in Sri Lanka Police",a:"Short tenure as IGP",w:"Brief command period",d:"—"},
{n:"20th",nm:"Rudra Rajasingham",rk:"Inspector General",t:"Mar 1982 – Mar 1985",p:"https://www.police.lk/wp-content/uploads/2024/10/16-198x248x0x0x198x248x1701340303.jpg",e:"—",j:"Career police officer; appointed 20th IGP",c:"Career in Sri Lanka Police",a:"Served during 1983 Black July riots",w:"Led police during 1983 anti-Tamil riots and aftermath",d:"—"},
{n:"19th",nm:"Ana Seneviratne",rk:"Inspector General",t:"Aug 1978 – Mar 1982",p:"https://www.police.lk/wp-content/uploads/2024/10/17-198x248x0x0x198x248x1701340305.jpg",e:"—",j:"Career police officer; appointed 19th IGP",c:"Career in Sri Lanka Police",a:"Served under J.R. Jayewardene government",w:"Led police during early UNP era",d:"—"},
{n:"18th",nm:"Stanley Senanayake",rk:"Inspector General",t:"Sep 1970 – Aug 1978",p:"https://www.police.lk/wp-content/uploads/2024/10/18-198x248x0x0x198x248x1701340306.jpg",e:"—",j:"Career police officer; appointed 18th IGP",c:"Career in Sri Lanka Police",a:"Served during 1971 JVP Insurrection",w:"Led police response to 1971 JVP Insurrection",d:"—"},
{n:"17th",nm:"Aleric Abeygunawardena",rk:"Inspector General",t:"Jul 1967 – Sep 1970",p:"https://www.police.lk/wp-content/uploads/2024/10/19-198x248x0x0x198x248x1701340307.jpg",e:"—",j:"Career police officer; appointed 17th IGP",c:"Career in Sri Lanka Police",a:"Served in post-independence era",w:"Led police during late 1960s",d:"—"},
{n:"16th",nm:"John Attygalle",rk:"Inspector General",t:"Jun 1966 – Jul 1967",p:"https://www.police.lk/wp-content/uploads/2024/10/20-198x248x0x0x198x248x1701340308.jpg",e:"—",j:"Career police officer; appointed 16th IGP",c:"Career in Sri Lanka Police",a:"Short tenure as IGP",w:"Brief command period",d:"—"},
{n:"15th",nm:"S.A. Dissanayake",rk:"Inspector General",t:"Feb 1963 – Jun 1966",p:"https://www.police.lk/wp-content/uploads/2024/10/21-198x248x0x0x198x248x1701340309.jpg",e:"—",j:"Career police officer; appointed 15th IGP",c:"Career in Sri Lanka Police",a:"Served during political instability of 1960s",w:"Led police during 1960s political crises",d:"—"},
{n:"14th",nm:"M. Walter F. Abeykoon",rk:"Inspector General",t:"May 1959 – Feb 1963",p:"https://www.police.lk/wp-content/uploads/2024/10/22-198x248x0x0x198x248x1701340310.jpg",e:"—",j:"Career police officer; appointed 14th IGP",c:"Career in Sri Lanka Police",a:"Served during late 1950s unrest",w:"Led police during late 1950s communal tensions",d:"—"},
{n:"13th",nm:"Osmund de Silva",rk:"Inspector General",t:"Jul 1955 – Apr 1959",p:"https://www.police.lk/wp-content/uploads/2024/10/23-198x248x0x0x198x248x1701340311.jpg",e:"—",j:"Career police officer; appointed 13th IGP",c:"Career in Sri Lanka Police",a:"Served during 1958 riots",w:"Led police during 1958 communal riots",d:"—"},
{n:"12th",nm:"Richard Aluwihare",rk:"Inspector General",t:"1946 – 1955",p:"https://www.police.lk/wp-content/uploads/2024/10/24-198x248x0x0x198x248x1701340312.jpg",e:"—",j:"Career police officer; appointed 12th IGP",c:"Career in Ceylon Police",a:"First Ceylonese IGP",w:"Led police through independence in 1948",d:"—"},
{n:"11th",nm:"Ranulph Bacon",rk:"Inspector General",t:"1944 – 1946",p:"https://www.police.lk/wp-content/uploads/2024/10/25-198x248x0x0x198x248x1701340313.jpg",e:"—",j:"British colonial police officer; appointed 11th IGP",c:"Colonial police service career",a:"Served at end of WWII",w:"Led police during late wartime period",d:"—"},
{n:"10th",nm:"Gordon Herbert Ramsay Halland",rk:"Inspector General",t:"1942 – 1944",p:"https://www.police.lk/wp-content/uploads/2024/10/26-198x248x0x0x198x248x1701340314.jpg",e:"—",j:"British colonial police officer; appointed 10th IGP",c:"Colonial police service career",a:"Served during WWII",w:"Led police during wartime",d:"—"},
{n:"9th",nm:"Philip Norton Banks",rk:"Inspector General",t:"1937 – 1942",p:"https://www.police.lk/wp-content/uploads/2024/10/27-198x248x0x0x198x248x1701340315.jpg",e:"—",j:"British colonial police officer; appointed 9th IGP",c:"Colonial police service career",a:"Served before and during WWII",w:"Led police during pre-war and early wartime",d:"—"},
{n:"8th",nm:"Herbert Dowbiggin",rk:"Inspector General",t:"1913 – 1937",p:"https://www.police.lk/wp-content/uploads/2024/10/28-198x248x0x0x198x248x1701340316.jpg",e:"—",j:"British colonial police officer; appointed 8th IGP",c:"Colonial police service career",a:"Longest-serving colonial IGP; introduced fingerprinting and modern policing methods to Ceylon",w:"Reformed and modernized Ceylon police over 24 years",d:"—"},
{n:"7th",nm:"Ivor Edward David",rk:"Inspector General",t:"1910 – 1913",p:"https://www.police.lk/wp-content/uploads/2024/10/29-198x248x0x0x198x248x1701340318.jpg",e:"—",j:"British colonial police officer; appointed 7th IGP",c:"Colonial police service career",a:"Served in early 20th century",w:"Led police during Edwardian era",d:"—"},
{n:"6th",nm:"Cyril Longden",rk:"Inspector General",t:"1905 – 1910",p:"https://www.police.lk/wp-content/uploads/2024/10/30-198x248x0x0x198x248x1701340319.jpg",e:"—",j:"British colonial police officer; appointed 6th IGP",c:"Colonial police service career",a:"Served in early 20th century",w:"Led police during colonial era",d:"—"},
{n:"5th",nm:"Albert De Wilton",rk:"Inspector General",t:"1902 – 1905",p:"https://www.police.lk/wp-content/uploads/2024/10/31-198x248x0x0x198x248x1701340320.jpg",e:"—",j:"British colonial police officer; appointed 5th IGP",c:"Colonial police service career",a:"Served in early 20th century",w:"Led police during colonial era",d:"—"},
{n:"4th",nm:"Louis Knollys",rk:"Inspector General",t:"1891 – 1902",p:"https://www.police.lk/wp-content/uploads/2024/10/32-198x248x0x0x198x248x1701340321.jpg",e:"—",j:"British colonial police officer; appointed 4th IGP",c:"Colonial police service career",a:"Served in late Victorian era",w:"Led police during colonial era",d:"—"},
{n:"3rd",nm:"George William Robert Campbell",rk:"Inspector General",t:"1873 – 1891",p:"https://www.police.lk/wp-content/uploads/2024/10/33-198x248x0x0x198x248x1701340322.jpg",e:"—",j:"British colonial police officer; re-appointed 3rd IGP",c:"Colonial police service career",a:"Second tenure as head of police; served 18 years",w:"Led police during late 19th century",d:"—"},
{n:"2nd",nm:"Frederick Richard Saunders",rk:"Inspector General",t:"1872 – 1873",p:"https://www.police.lk/wp-content/uploads/2024/10/34-198x248x0x0x198x248x1701767107.jpg",e:"—",j:"British colonial police officer; appointed 2nd IGP",c:"Colonial police service career",a:"Short tenure as head of police",w:"Brief command period",d:"—"},
{n:"1st",nm:"George William Robert Campbell",rk:"Inspector General",t:"Sep 1866 – 1872",p:"https://www.police.lk/wp-content/uploads/2024/10/33-198x248x0x0x198x248x1701340322.jpg",e:"—",j:"British police officer from India; appointed first Chief Superintendent of Police in Ceylon",c:"Former chief of police in Ratnagiri, India; established the Ceylon Police Force",a:"First Inspector General of Police; founded the Ceylon Police Force on 3 Sep 1866",w:"Established the Ceylon Police Force from the Fiscal system",d:"—"}
]
};

// ========== MODAL FUNCTIONS ==========
function openCommanderModal(branch,idx){
const c=DB[branch][idx];
if(!c)return;
const branchColors={army:'military',navy:'navy',airforce:'afblue',police:'police'};
const bc=branchColors[branch]||'military';
const initials=c.nm.split(' ').map(w=>w[0]).join('').substring(0,2).toUpperCase();
const controversyHTML=c.co?'<div class="mt-4 bg-red-950/30 border border-red-800/50 rounded-xl p-4"><h4 class="font-heading text-sm font-bold text-red-400 mb-2">CONTROVERSIES / NOTABLE EVENTS</h4><p class="text-gray-400 text-sm">'+c.co+'</p></div>':'';
const rankBadgeMap={
army:{
'Field Marshal':'https://en.wikipedia.org/wiki/Special:Redirect/file/Sri_Lanka-army-OF-10.svg?width=160',
'General':'https://en.wikipedia.org/wiki/Special:Redirect/file/Sri_Lanka-army-OF-9.svg?width=160',
'General (Deshamanya)':'https://en.wikipedia.org/wiki/Special:Redirect/file/Sri_Lanka-army-OF-9.svg?width=160',
'Lieutenant General':'https://en.wikipedia.org/wiki/Special:Redirect/file/Sri_Lanka-army-OF-8.svg?width=160',
'Major General':'https://en.wikipedia.org/wiki/Special:Redirect/file/Sri_Lanka-army-OF-7.svg?width=160',
'Brigadier':'https://en.wikipedia.org/wiki/Special:Redirect/file/Sri_Lanka-army-OF-6.svg?width=160'
},
navy:{
    'Admiral':'https://en.wikipedia.org/wiki/Special:Redirect/file/15-Sri_Lanka_Navy-ADM.svg?width=160',
    'Vice Admiral':'https://en.wikipedia.org/wiki/Special:Redirect/file/14-Sri_Lanka_Navy-VADM.svg?width=160',
    'Admiral of the Fleet':'https://en.wikipedia.org/wiki/Special:Redirect/file/16-Sri_Lanka_Navy-FADM.svg?width=160',
    'Rear Admiral':'https://en.wikipedia.org/wiki/Special:Redirect/file/13-Sri_Lanka_Navy-RADM.svg?width=160',
    'Commodore':'https://en.wikipedia.org/wiki/Special:Redirect/file/12-Sri_Lanka_Navy-CDRE.svg?width=160',
    'Captain':'https://en.wikipedia.org/wiki/Special:Redirect/file/11-Sri_Lanka_Navy-CAPT.svg?width=160'
  },
  police:{
    'Inspector General':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sri_Lanka-Police-Inspector_General_of_Police.svg'
  },
airforce:{
'Marshal of the SLAF':'https://en.wikipedia.org/wiki/Special:Redirect/file/UK-Air-OF10.svg?width=160',
'Air Chief Marshal':'https://en.wikipedia.org/wiki/Special:Redirect/file/UK-Air-OF9.svg?width=160',
'Air Marshal':'https://en.wikipedia.org/wiki/Special:Redirect/file/UK-Air-OF8.svg?width=160',
'Air Vice Marshal':'https://en.wikipedia.org/wiki/Special:Redirect/file/UK-Air-OF7.svg?width=160',
'Group Captain':'https://en.wikipedia.org/wiki/Special:Redirect/file/UK-Air-OF5.svg?width=160'
}};
const rankCodeMap={'Field Marshal':'OF-10','General':'OF-9','General (Deshamanya)':'OF-9','Lieutenant General':'OF-8','Major General':'OF-7','Brigadier':'OF-6','Admiral of the Fleet':'OF-10','Admiral':'OF-9','Vice Admiral':'OF-8','Rear Admiral':'OF-7','Commodore':'OF-6','Captain':'OF-5','Marshal of the SLAF':'OF-10','Air Chief Marshal':'OF-9','Air Marshal':'OF-8','Air Vice Marshal':'OF-7','Group Captain':'OF-5'};
const rankBadgeUrl=(rankBadgeMap[branch]&&rankBadgeMap[branch][c.rk])||'';
const rankBadgeHTML=rankBadgeUrl?`<img src="${rankBadgeUrl}" alt="${c.rk} Rank" class="w-16 h-16 object-contain absolute top-4 right-16" onerror="this.style.display='none'">`:`<div class="absolute top-4 right-16 bg-${bc}-800/60 text-${bc}-300 text-xs font-bold px-2 py-1 rounded">${rankCodeMap[c.rk]||c.rk}</div>`;
document.getElementById('commanderModalContent').innerHTML=`
<div class="bg-gradient-to-br from-${bc}-900/50 to-${bc}-950/50 p-6 border-b border-${bc}-800">
<div class="flex items-center gap-4">
<div class="w-16 h-16 rounded-full bg-${bc}-800 border-2 border-${bc}-600 flex items-center justify-center flex-shrink-0 overflow-hidden">
${c.p?`<img src="${c.p}" alt="${c.nm}" class="w-full h-full object-cover" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><span style="display:none" class="w-full h-full items-center justify-center">${initials}</span>`:`<span class="text-${bc}-400 font-bold text-xl">${initials}</span>`}
</div>
<div>
<span class="px-3 py-1 bg-${bc}-800/80 text-${bc}-300 text-xs font-bold rounded-full">${c.n}</span>
<h3 class="font-heading text-2xl font-bold text-white mt-1">${c.nm}</h3>
<p class="text-${bc}-400 font-mono text-sm">${c.rk} · ${c.t}</p>
</div>
</div>
${rankBadgeHTML}
</div>
<div class="p-6 space-y-4">
<div><h4 class="font-heading text-sm font-bold text-${bc}-400 mb-1">EDUCATION</h4><p class="text-gray-300 text-sm">${c.e}</p></div>
<div><h4 class="font-heading text-sm font-bold text-${bc}-400 mb-1">HOW HE JOINED</h4><p class="text-gray-300 text-sm">${c.j}</p></div>
<div><h4 class="font-heading text-sm font-bold text-${bc}-400 mb-1">CAREER POSITIONS</h4><p class="text-gray-300 text-sm">${c.c}</p></div>
<div><h4 class="font-heading text-sm font-bold text-${bc}-400 mb-1">NOTABLE ACHIEVEMENTS</h4><p class="text-gray-300 text-sm">${c.a}</p></div>
<div><h4 class="font-heading text-sm font-bold text-${bc}-400 mb-1">AS COMMANDER</h4><p class="text-gray-300 text-sm">${c.w}</p></div>
${c.u?'<div><h4 class="font-heading text-sm font-bold text-'+bc+'-400 mb-1">UNIT</h4><p class="text-gray-300 text-sm">'+c.u+'</p></div>':''}
<div><h4 class="font-heading text-sm font-bold text-${bc}-400 mb-1">DECORATIONS & AWARDS</h4><p class="text-gray-300 text-sm">${c.d}</p></div>
${controversyHTML}
</div>`;
const modal=document.getElementById('commanderModal');
modal.classList.remove('hidden');
modal.classList.add('flex');
lockScroll();
}
function closeCommanderModal(){
const modal=document.getElementById('commanderModal');
modal.classList.add('hidden');
modal.classList.remove('flex');
unlockScroll();
}

function renderCommanderCard(branch, idx){
const c=DB[branch][idx];
if(!c)return '';
const branchColors={army:'military',navy:'navy',airforce:'afblue',police:'police'};
const bc=branchColors[branch]||'military';
const initials=c.nm.split(' ').map(w=>w[0]).join('').substring(0,2).toUpperCase();
const photoHTML=c.p?`<img src="${c.p}" alt="${c.nm}" class="w-full h-full object-cover" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><span style="display:none" class="w-full h-full items-center justify-center">${initials}</span>`:`<span class="text-${bc}-400 font-bold text-xl">${initials}</span>`;
return `<div class="bg-${bc}-950/50 rounded-lg p-4 border border-${bc}-800 cursor-pointer hover:bg-${bc}-800/30 transition-colors" onclick="openCommanderModal('${branch}',${idx})">
<div class="text-${bc}-400 text-xs font-mono mb-1">${c.n} COMMANDER</div>
<div class="flex items-center gap-4 mt-2">
<div class="w-16 h-16 rounded-full bg-${bc}-800 border-2 border-${bc}-600 flex items-center justify-center flex-shrink-0 overflow-hidden">
${photoHTML}
</div>
<div>
<p class="text-white font-heading text-lg font-bold">${c.nm} ${c.d.split(',')[0]}</p>
<p class="text-gray-500 text-xs">${c.d}</p>
<p class="text-gray-500 text-xs mt-1">${c.t}</p>
</div>
</div>
</div>`;
}
